spring:
  #  config:
  #    activate:
  #      on-profile: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dreamStore
    password: root
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: none
#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          nodeValue: trace
#          descriptor:
#            sql: trace
#        SQL: debug

#  config:
#    activate:
#      on-profile: test
#  h2:
#    console:
#      enabled: true
#  jpa:
#    database: h2
#    generate-ddl: off
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb;MODE=MySQL;
#    username: SA
#    password:
#    initialization-mode: always
#    schema: classpath:schema-h2.sql
#    data: classpath:data-h2.sql